[2025-03-14T01:04:25.665+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-14T01:04:25.713+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.test_validating_data_silver_layer.erp_cust scheduled__2025-03-14T00:45:00+00:00 [queued]>
[2025-03-14T01:04:25.729+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.test_validating_data_silver_layer.erp_cust scheduled__2025-03-14T00:45:00+00:00 [queued]>
[2025-03-14T01:04:25.729+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-03-14T01:04:25.758+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): test_validating_data_silver_layer.erp_cust> on 2025-03-14 00:45:00+00:00
[2025-03-14T01:04:25.783+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2121) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-14T01:04:25.785+0000] {standard_task_runner.py:63} INFO - Started process 2133 to run task
[2025-03-14T01:04:25.789+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'test_validating_data_silver_layer.erp_cust', 'scheduled__2025-03-14T00:45:00+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp397cssba']
[2025-03-14T01:04:25.795+0000] {standard_task_runner.py:91} INFO - Job 227: Subtask test_validating_data_silver_layer.erp_cust
[2025-03-14T01:04:25.906+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.test_validating_data_silver_layer.erp_cust scheduled__2025-03-14T00:45:00+00:00 [running]> on host 2b35ac7f54da
[2025-03-14T01:04:26.157+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='test_validating_data_silver_layer.erp_cust' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T00:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-14T00:45:00+00:00'
[2025-03-14T01:04:26.162+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-14T01:04:26.193+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-14T01:04:26.195+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt test --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt/sales --models erp_cust']
[2025-03-14T01:04:26.241+0000] {subprocess.py:86} INFO - Output:
[2025-03-14T01:04:31.671+0000] {subprocess.py:93} INFO - [0m01:04:31  Running with dbt=1.9.3
[2025-03-14T01:04:32.797+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/snowflake/connector/options.py:108: UserWarning: You have an incompatible version of 'pyarrow' installed (19.0.1), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-03-14T01:04:32.798+0000] {subprocess.py:93} INFO -   warn_incompatible_dep(
[2025-03-14T01:04:33.945+0000] {subprocess.py:93} INFO - [0m01:04:33  Registered adapter: snowflake=1.9.2
[2025-03-14T01:04:35.681+0000] {subprocess.py:93} INFO - [0m01:04:35  Found 10 models, 41 data tests, 6 sources, 855 macros
[2025-03-14T01:04:35.691+0000] {subprocess.py:93} INFO - [0m01:04:35
[2025-03-14T01:04:35.691+0000] {subprocess.py:93} INFO - [0m01:04:35  Concurrency: 2 threads (target='dev')
[2025-03-14T01:04:35.692+0000] {subprocess.py:93} INFO - [0m01:04:35
[2025-03-14T01:04:36.866+0000] {subprocess.py:93} INFO - [0m01:04:36  1 of 3 START test accepted_values_erp_cust_Gender__Male__Female__n_a ........... [RUN]
[2025-03-14T01:04:36.867+0000] {subprocess.py:93} INFO - [0m01:04:36  2 of 3 START test dbt_expectations_expect_column_values_to_be_of_type_erp_cust_birth_date__date  [RUN]
[2025-03-14T01:04:37.201+0000] {subprocess.py:93} INFO - [0m01:04:37  2 of 3 PASS dbt_expectations_expect_column_values_to_be_of_type_erp_cust_birth_date__date  [[32mPASS[0m in 0.33s]
[2025-03-14T01:04:37.205+0000] {subprocess.py:93} INFO - [0m01:04:37  3 of 3 START test not_null_erp_cust_customer_id ................................ [RUN]
[2025-03-14T01:04:37.268+0000] {subprocess.py:93} INFO - [0m01:04:37  1 of 3 PASS accepted_values_erp_cust_Gender__Male__Female__n_a ................. [[32mPASS[0m in 0.40s]
[2025-03-14T01:04:37.430+0000] {subprocess.py:93} INFO - [0m01:04:37  3 of 3 PASS not_null_erp_cust_customer_id ...................................... [[32mPASS[0m in 0.22s]
[2025-03-14T01:04:37.757+0000] {subprocess.py:93} INFO - [0m01:04:37
[2025-03-14T01:04:37.759+0000] {subprocess.py:93} INFO - [0m01:04:37  Finished running 3 data tests in 0 hours 0 minutes and 2.06 seconds (2.06s).
[2025-03-14T01:04:38.014+0000] {subprocess.py:93} INFO - [0m01:04:38
[2025-03-14T01:04:38.015+0000] {subprocess.py:93} INFO - [0m01:04:38  [32mCompleted successfully[0m
[2025-03-14T01:04:38.015+0000] {subprocess.py:93} INFO - [0m01:04:38
[2025-03-14T01:04:38.016+0000] {subprocess.py:93} INFO - [0m01:04:38  Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2025-03-14T01:04:39.224+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-14T01:04:39.225+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-14T01:04:39.254+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=test_validating_data_silver_layer.erp_cust, execution_date=20250314T004500, start_date=20250314T010425, end_date=20250314T010439
[2025-03-14T01:04:39.305+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-14T01:04:39.337+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T01:04:39.338+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
